### ISSUE TITLE
IITemRenderer Incompatabilities

### ISSUE THREAD

**Issue by jredfox** [TheCBProject/CodeChickenLib#190]
when two mods replace the IITemRenderer one will take over the other will simply not work
https://github.com/jredfox/evilnotchlib/issues/11

As you can see my mod fired after yours and the ender storage tanks are invisible. 

Solution: we need to not replace one another renderers. I don't know if we both need to go asm or just one or the other. We could write a universal class which will have hashmaps between item and IITemRender as an array I don't know we could figure something out. 

Maybe we could just simply use both the same code. I think you will like the setup it was written by elix_x 
https://github.com/jredfox/evilnotchlib/tree/master/src/main/java/com/elix_x/itemrender

**Comment by covers1624** [comment]
No, you are not overriding the renderer properly, I'm careful and delegate any render calls to the renderer im overriding, you simply need to do the same, its not rocket science, this is entirely on your end.

**Comment by covers1624** [comment]
Also, Forge now has hooks, Item.setTESIR or something like that, use that hook, IItemRenderer stuff in CCL will be rewritten in 1.13.

**Comment by jredfox** [comment]
Your overriding the RenderItem Completely I was going to convert mine into asm line injections but, your class of `CCRenderItem` is ruining it.

I use TransformType.GUI and other transform types for my IITemRenderers. Could it be possible for you to convert to ASM as well? You can add an interface and cast for additional methods. You can easily add methods in memory then patch the local variable of "this" and patch any and all object instructions. After you have done that then make sure your interface you attach to the class has all your new methods you want to mess with.

**Comment by jredfox** [comment]
or there is a simpler way for us to add compat.

**Have your RenderItem object call super() on everything if your item isn't mapped and doesn't need to override could you do that for me please? thanks I will make the edits the the RenderItem.class on my side**

If you don't want to call super call your render item object you store in your wrapper class render item if you have no overrides. Currently the issue is fixed on my side but, not yours. *I did a method replace test and now yours is the one overriding mine*

**Comment by covers1624** [comment]
You still don't understand and I'm sick of your shit, pleas just read my replays, extend RenderItem, do what ccl's does, look in my client proxy for how I initialize it and it will work, you don't need asm, parent override classes are not rocket science.

**Comment by jredfox** [comment]
no I didn't understand what you were doing that's why I asked. Don't worry I figured it out. Yeah I guess I don't need the asm but, it's already do. 

I might have understood sooner if you simple said create a wrapper RenderItem and use that. You confused me and said you could grab and use delegates or something there were none.

**Comment by covers1624** [comment]
Literelly anyone would have followed my explanation. Parent overrides are a standard in the community..

**Comment by jredfox** [comment]
thanks anyways for pointing out it was my logic that was the error
