### ISSUE TITLE
NCDFE on IItemRenderer with latest CCL

### ISSUE THREAD

**Issue by robaimes** [TheCBProject/CodeChickenLib#9]
With CCL installed on the client, and no mods that depend on it, this error occurs: http://pastebin.com/vWUFmqcj

Even with **_JUST**_ CCL installed, this occurs: http://pastebin.com/kSiiQDYs

This is only occurring since the refcator in version `2.4.1.97`. Did you perhaps forget something or is there an issue elsewhere?

**Comment by covers1624** [comment]
I moved stuff in CCL. i have pushed to DE, ill be pushing a release of everything tomorrow, and ill get @brandon3055 to do the same.

**Comment by robaimes** [comment]
Alright sweet. So for now, just use the older versions? I'm assuming the newest versions of NEI and ES rely on this?

**Comment by covers1624** [comment]
Yes, brandon just pushed to curse.

**Comment by robaimes** [comment]
So in terms of this issue, and #10 - Which version should I be looking out for? Currently `2.4.1.98` is crashing the same way.

**Comment by Gepett0** [comment]
Tried the version ending .98 too, still crashing. Sorry to say...

**Comment by covers1624** [comment]
Just roll back.. im working on something to debug it, it must be another mod using IIR

**Comment by robaimes** [comment]
As I said in OP, even if only CCL is installed this crash occurs

**Comment by covers1624** [comment]
check latest commit message

**Comment by Bodidl** [comment]
CodeChickenLib-1.10.2-2.4.1.101-universal works both on my server and client. Thank you! Think I only have Draconic Evolution that uses it.

**Comment by robaimes** [comment]
Yep, fixed now! Thanks :)
